version: "3"
services:
  nginx:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./conf/hosts:/etc/hosts
      - ./certs:/etc/nginx/certs
